<script type="text/x-magento-init">
    {
        "[data-role=priceBox]": {
          "finance": {
            "triggerEvent": "click"
          }
        }
    }
</script>

<a href="javascript:void(0);" id="msrp-popup-1xxc" class="action map-show-info">Finance options</a>
<div id="popup-modal-finance" class="map-popup">
    <div class="popup-header">
        <strong class="title" id="map-popup-heading-finance">Finance</strong>
    </div>
    <div class="popup-content">
        <div class="map-help-text" id="map-popup-text-finance">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ullamcorper, neque vel malesuada molestie, justo justo sollicitudin leo, eu auctor arcu est in ligula. Ut rutrum aliquam magna dapibus viverra. Suspendisse non mollis velit, eu aliquet felis. Morbi molestie ornare ante id ornare. In eleifend nisl sit amet massa venenatis tincidunt. In finibus quis ligula eget vulputate. Ut laoreet leo vitae convallis varius. Sed consequat tincidunt lorem, ut vehicula lorem consequat ac.
        </div>
    </div>
</div>
